# Generated by Django 3.0.6 on 2020-09-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200924_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='_class',
            new_name='m_class',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_class',
            new_name='m_class',
        ),
    ]
