# Generated by Django 3.0.6 on 2020-09-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200924_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='m_class',
        ),
        migrations.AddField(
            model_name='item',
            name='m_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Class'),
        ),
    ]
