# Generated by Django 3.0.6 on 2020-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200924_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='modification',
            field=models.IntegerField(default=1),
        ),
    ]
