# Generated by Django 3.0.6 on 2020-09-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='m_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Class'),
        ),
        migrations.AlterField(
            model_name='score',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Item'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='m_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Class'),
        ),
    ]
